### PR TITLE
Deleted names on the bottom

### PR DESCRIPTION
**Pull request by zjuradoq**
Pull request to address issue #21 

Can Assignee review and merge pull request if you agree. (As practice as well for our next edit for the protocol.)

### CODE REVIEW

**Comment by murrayrm** [comment]
@zjuradoq Can you update your PR to use the version of `protocol-list.md` that you just approved as a merge.  That should get rid of the conflict.

Also, while you are in the file (after updating), it would be useful to change the protocol description that was added in PR #24 so that it wraps lines at 72 characters.  Otherwise everything is on a single line and hard to edit in GitHub.

**Comment by zjuradoq** [comment]
It says that the version from my branch and the protocol-list.md are up to date.

**Comment by murrayrm** [comment]
Your branch is up to date, but you don't have the latest updates from the master branch.  Try running
```
git pull upstream master
```
This will fetch and merge the latest changes from the master branch into yours.  You'll probably get a conflict, but you should be able to resolve it locally and then commit the changes.

**Comment by zjuradoq** [comment]
This pull request should be covered by PR #29.

**Comment by murrayrm** [comment]
Closing this PR since it is covered by PR #29.

**Pull request closed without merging**
